package edu.neu.madcourse.skilift.models;

// Contains all of the ski resorts in the USA
public class Resorts {

    public static final String[] resortArray = {
            "49 Degrees North Mountain Resort",
            "Abenaki",
            "Adventure Mountain – Greenland",
            "Afton Alps",
            "Al Quaal",
            "Aldis Hill Park – St. Albans",
            "Alpental",
            "Alpine Meadows",
            "Alpine Mountain Ski & Snow Tubing Center  (temporarily closed)",
            "Alpine Valley Ohio",
            "Alpine Valley Resort – Elkhorn",
            "Alpine Valley – White Lake",
            "Alta",
            "Alta Sierra – Shirley Meadows",
            "Alyeska Resort – Girdwood",
            "Andes Tower Hills",
            "Angel Fire",
            "Antelope Butte",
            "Anthony Lakes Mountain Resort",
            "Apache",
            "Appalachian Ski Mountain",
            "Arapahoe Basin",
            "Arctic Valley",
            "Arizona Snowbowl",
            "Ascutney Mountain",
            "Aspen Highlands",
            "Aspen Mountain",
            "Attitash Mountain Resort",
            "Ausblick – Sussex",
            "Badger Mountain",
            "Badger Pass",
            "Bald Mountain",
            "Bald Mountain – Sun Valley",
            "Bear Creek Mountain Resort",
            "Bear Mountain – Big Bear Lake",
            "Bear Paw Ski Bowl",
            "Bear Valley",
            "Bear's Den Mountain – Fort Ransom  (temporarily closed)",
            "Bearfire Resort – Dallas-Fort Worth (planned) (indoor ski area)",
            "Beartooth Basin",
            "Beartown",
            "Beaver Creek",
            "Beaver Mountain",
            "Beech Mountain",
            "Belleayre Mountain",
            "Berkshire East",
            "Big Bear at Masthope Mountain",
            "Big Boulder",
            "Big Creek Ski Area",
            "Big Powderhorn Mountain",
            "Big Sky Resort",
            "Big Snow American Dream (indoor ski area)",
            "Big Squaw",
            "Big Tupper – Tupper Lake",
            "Bigrock Mountain",
            "Bittersweet",
            "Black Mountain – Jackson",
            "Black Mountain – Rumford",
            "Black Rapid",
            "Blackhawk Ski Club – Middleton",
            "Blackjack",
            "Blacktail Mountain",
            "Blandford  (temporarily closed)",
            "Blue Hills",
            "Blue Knob",
            "Blue Mountain",
            "Bluewood",
            "Bogus Basin",
            "Bolton Valley",
            "Boreal",
            "Boston Mills",
            "Bottineau Winter Park",
            "Bousquet",
            "Bowe's Ski Hill – Steamboat Springs",
            "Boyce Park",
            "Boyne Mountain",
            "Bradford",
            "Brandywine",
            "Brantling Ski Slopes",
            "Breckenridge",
            "Bretton Woods",
            "Brian Head",
            "Bridger Bowl – Bozeman",
            "Brighton",
            "Bristol Mountain",
            "Bromley Mountain",
            "Bruce Mound",
            "Brundage Mountain",
            "Bryce Resort",
            "Buck Hill Ski Area",
            "Buckhorn Ski and Snowboard Club",
            "Buena Vista",
            "Buffalo Ski Club",
            "Burke Mountain",
            "Buttermilk Mountain",
            "Butternut",
            "Caberfae Peaks",
            "Camden Snow Bowl",
            "Camelback",
            "Camp 10",
            "Campgaw Mountain",
            "Campton Mountain",
            "Canaan Valley",
            "Cannon Mountain",
            "Cannonsburg",
            "Carson Ski Resort",
            "Cascade Mountain",
            "Cascade Powder Guides",
            "Cataloochee",
            "Catamount",
            "Cazenovia",
            "Challenge Mountain – Walloon Lake",
            "Cherry Peak",
            "Chester Bowl",
            "Chestnut Mountain",
            "China Peak",
            "Christie Mountain",
            "Christmas Mountain",
            "Cimarron Mountain Club",
            "Cloudcroft",
            "Cloudmont",
            "Cochran",
            "Cockaigne",
            "Coffee Mill",
            "Cooper",
            "Cooper Spur",
            "Copper Mountain",
            "Coppervale",
            "Cottonwood Butte",
            "Cranmore Mountain Resort",
            "Crested Butte",
            "Crotched Mountain",
            "Crystal Mountain (MI)",
            "Crystal Mountain (WA)",
            "Cuchara Mountain Park  (temporarily closed)",
            "Dartmouth Skiway",
            "Deer Mountain  (temporarily closed)",
            "Deer Valley",
            "Denton Hill State Park  (temporarily closed)",
            "Detroit Mountain",
            "Devil's Head",
            "Diamond Peak",
            "Diamond Peaks",
            "Discovery Ski Area",
            "Dodge Ridge",
            "Dollar Mountain – Sun Valley",
            "Donner Ski Ranch",
            "Dry Hill",
            "Dynamite Hill – Chestertown",
            "Eagle Island Park",
            "Eagle Point",
            "Eagle Rock",
            "Eaglecrest – Juneau",
            "Eaton Mountain  (temporarily closed)",
            "Echo Mountain Park – Idaho Springs",
            "Echo Valley – Lake Chelan",
            "Eldora Mountain",
            "Elk Mountain",
            "Elk Ridge – Williams  (temporarily closed)",
            "Elko Snobowl",
            "Fairfax Peak (planned) (indoor ski area)",
            "Farr's Hill – Randolph",
            "Ferguson Ridge",
            "Fort Wainwright/​Birch Hill – Fairbanks",
            "Four Lakes",
            "Four Seasons",
            "Fox Hill",
            "Frost Fire Park",
            "Giants Ridge",
            "Gore Mountain",
            "Granby Ranch",
            "Grand Geneva",
            "Grand Targhee",
            "Granite Gorge  (temporarily closed)",
            "Granite Peak at Rib Mountain State Park",
            "Granlibakken",
            "Great Bear Ski Valley",
            "Great Divide",
            "Great Northern Powder Guides",
            "Greek Peak",
            "Green Mountain – Bush Creek Ranch",
            "Gunstock",
            "H2O Guides",
            "Hanson Hills",
            "Haystack Mountain – The Hermitage Club",
            "Heavenly",
            "Heiliger Huegel – Hubertus",
            "Hermon Mountain",
            "Hesperus Ski Area",
            "Hickory  (temporarily closed)",
            "Hidden Valley (MO)",
            "Hidden Valley (PA)",
            "Hillberg",
            "Hilltop – Anchorage",
            "Hogadon Ski Area",
            "Holiday Mountain (NY)",
            "Holiday Valley",
            "Holimont",
            "Homewood Mountain Resort",
            "Hoodoo Ski Area",
            "Howelsen Hill – Steamboat Springs",
            "Huff Hills",
            "Hunt Hollow Ski Club",
            "Hunter Mountain",
            "Huntington",
            "Hurricane Ridge",
            "Hyland Hills",
            "Indian Lake",
            "Indianhead Mountain",
            "Inside Ski Training Center – Leesburg (dry slopes)",
            "Jack Frost Mountain",
            "Jackson Hole",
            "Jay Peak",
            "Jerry's Heliski Alaska",
            "Jiminy Peak",
            "John & Melissa Besse Sports Park – Gladstone",
            "June Mountain",
            "Kelly Canyon",
            "Kendall Mountain – Silverton",
            "Kettlebowl",
            "Keyes Peak",
            "Keystone",
            "Killington",
            "King Pine – Purity Spring Resort",
            "Kirkwood",
            "Kissing Bridge",
            "Labrador Mountain",
            "Lake City Ski Hill",
            "Las Vegas Ski and Snowboard Resort – Lee Canyon",
            "Las Vegas Wet (planned) (indoor ski area)",
            "Laurel Mountain",
            "Leavenworth Ski Hill",
            "Liberty Mountain",
            "Little Ski Hill",
            "Little Switzerland",
            "Living Memorial Park – Brattleboro",
            "Lonesome Pine Trails – Fort Kent",
            "Lookout Pass",
            "Loon Mountain",
            "Lost Trail Powder Mountain",
            "Lost Valley",
            "Loup Loup Ski Bowl",
            "Loveland",
            "Lutsen Mountains",
            "Lyndon Outing Club",
            "Lynx Creek",
            "Mad River Glen",
            "Mad River Mountain",
            "Magic Mountain",
            "Magic Mountain Resort",
            "Mammoth Mountain",
            "Maple Ski Ridge",
            "Maple Valley  (temporarily closed)",
            "Marquette Mountain",
            "Massanutten",
            "Maverick Mountain",
            "Mayflower Mountain Resort (planned)",
            "McCauly Mountain",
            "McIntyre",
            "Meadowlark Ski Lodge",
            "Meany Lodge",
            "Middlebury College Snow Bowl",
            "Missaukee Mountain",
            "Mohawk Mountain",
            "Monarch",
            "Mont du Lac",
            "Mont Ripley",
            "Montage Mountain Resort",
            "Montana Snowbowl",
            "Moose Mountain",
            "Mott Mountain",
            "Mount Greylock – South Williamstown",
            "Mount Peter",
            "Mount Pleasant",
            "Mount Prospect – Lancaster",
            "Mount Ski Gull",
            "Mount Snow",
            "Mountain Creek – Vernon",
            "Mountain High East",
            "Mountain High North",
            "Mountain High West",
            "Mt. Abram",
            "Mt. Ashland",
            "Mt. Ashwabay – Salmo",
            "Mt. Bachelor",
            "Mt. Bailey",
            "Mt. Baker",
            "Mt. Baldy",
            "Mt. Bohemia",
            "Mt. Brighton",
            "Mt. Crescent",
            "Mt. Eustis – Littleton  (temporarily closed)",
            "Mt. Eyak",
            "Mt. Holiday",
            "Mt. Holly",
            "Mt. Hood Meadows",
            "Mt. Hood Skibowl",
            "Mt. Jefferson",
            "Mt. Kato",
            "Mt. La Crosse",
            "Mt. Lemmon Ski Valley",
            "Mt. McSauba",
            "Mt. Pisgah",
            "Mt. Rose",
            "Mt. Shasta Ski Park",
            "Mt. Southington",
            "Mt. Spokane",
            "Mt. Sunapee",
            "Mt. Waterman",
            "Mt. Zion Hill",
            "Mulligan's Hollow Ski Bowl",
            "Mystic Mountain – Farmington",
            "Nashoba Valley",
            "Navarino Hills  (temporarily closed)",
            "Nordic Mountain",
            "Nordic Valley",
            "North Bicentennial Park  (temporarily closed)",
            "North Cascade Heliskiing – Mazama",
            "Northeast Slopes – East Corinth",
            "Northstar California Resort",
            "Norway Mountain",
            "Nub's Nob Ski Area",
            "Nutt Hill – Plymouth",
            "Oak Mountain",
            "Ober Gatlinburg",
            "Oglebay Resort",
            "Okemo",
            "Otis Ridge",
            "Otsego – Gaylord",
            "Pajarito Mountain",
            "Palisades Tahoe",
            "Pando Park  (temporarily closed)",
            "Paoli Peaks",
            "Park City",
            "Pats Peak",
            "Paul Bunyan Ski Hill",
            "Pebble Creek",
            "Peek'n Peak",
            "Perfect North Slopes",
            "Petoskey Winter Sports Park",
            "Pico Mountain",
            "Pine Creek",
            "Pine Knob",
            "Pine Mountain",
            "Pinnacle Park – Pittsfield",
            "Plattekill",
            "Plumas Eureka Ski Bowl",
            "Plumtree (Fawnridge) – Lake Carroll",
            "Points North Heli Adventures",
            "Polar Peak",
            "Pomerelle",
            "Porcupine Mountain",
            "Powder Mountain",
            "Powder Ridge",
            "Powder Ridge Mountain Park & Resort",
            "Powderbird",
            "Powderhorn",
            "Powderhouse Hill – South Berwick",
            "Powers Bluff",
            "Purgatory – Durango",
            "Quadna Mountain",
            "Quechee Lakes Ski Area",
            "Quoggy Jo Ski Center – Presque Isle",
            "Ragged Mountain",
            "Red Hill – Moultonborough",
            "Red Lodge Mountain",
            "Red River",
            "Riverside Hills",
            "Rocking Horse Ranch",
            "Rotarun",
            "Roundtop",
            "Royal Mountain",
            "Ruby Mountain",
            "Saddleback",
            "Sahalie Ski Club",
            "Salmonberry – Valdez",
            "Sand Master Park – Florence (sand ski area)",
            "Sandia Peak",
            "Santa Fé",
            "Sapphire Valley",
            "Sawmill Mountain Resort",
            "Schweitzer Mountain Resort",
            "Scotch Valley Resort  (temporarily closed)",
            "Seven Oaks",
            "Seven Springs",
            "Shanty Creek Resorts – Schuss Mountain",
            "Shanty Creek Resorts – Summit Mountain",
            "Shawnee Mountain",
            "Shawnee Peak",
            "Showdown",
            "Sierra at Tahoe",
            "Silver Mountain",
            "Silverton Mountain",
            "Sipapu",
            "Sitzmark",
            "Skeetawk – Hatcher Pass",
            "Ski Brule",
            "Skiland – Mt. Aurora",
            "Sky Tavern",
            "Skyline – Friendship",
            "Sleeping Giant",
            "Smugglers' Notch",
            "Snow Creek",
            "Snow King Mountain – Jackson",
            "Snow Ridge",
            "Snow Snake",
            "Snow Summit – Big Bear Lake",
            "Snow Trails",
            "Snow Valley",
            "Snowbasin",
            "Snowbird",
            "Snowhaven",
            "Snowmass",
            "Snowshoe Mountain",
            "Snowstar",
            "Snowy Range",
            "Snöbahn – Centennial",
            "Soda Springs",
            "Soldier Mountain",
            "Solitude",
            "Song Mountain",
            "Spirit Mountain",
            "Spout Springs  (temporarily closed)",
            "Spring Mountain",
            "Spruce Mountain – Jay",
            "Stagecoach Mountain  (temporarily closed)",
            "Standing Rocks",
            "Steamboat",
            "Stevens Pass",
            "Storrs Hill – Lebanon",
            "Stover Mountain",
            "Stowe",
            "Stratton",
            "Sugar Bowl",
            "Sugar Mountain",
            "Sugarbush",
            "Sugarloaf",
            "Suicide Six",
            "Sunburst",
            "Sundance",
            "Sunday River",
            "Sundown",
            "Sundown Mountain Resort",
            "Sunlight Mountain",
            "Sunrise Park",
            "Sunset Ski Area",
            "Swain",
            "Swiss Valley",
            "Tahoe Donner",
            "Tamarack Resort",
            "Taos",
            "Telluride",
            "Tenney Mountain  (temporarily closed)",
            "Terry Peak",
            "Teton Pass",
            "The Balsams  (temporarily closed)",
            "The Highlands at Harbor Springs",
            "The Homestead Resort",
            "The Omni Homestead",
            "The Ridge – Le Roy",
            "The Rock Snowpark",
            "The Summit at Snoqualmie",
            "The Whitecap Mountains",
            "Thunder Ridge",
            "Timber Ridge",
            "Timberline",
            "Timberline Mountain",
            "Timberline Summit Pass",
            "Titcomb Mountain",
            "Titus Mountain",
            "Toggenburg Ski Center  (temporarily closed)",
            "Treetops",
            "Triangle Sports Area – Green Bay",
            "Trollhaugen",
            "Turner Mountain",
            "Tussey Mountain",
            "Tyrol Basin – Mt Horeb",
            "Utah Olympic Park",
            "Vail",
            "Val Bialas Ski Center – Utica",
            "Valdez Heli-Ski Guides",
            "Veterans Memorial – Franklin",
            "Villa Olivia – Bartlett",
            "Villa Roma",
            "Wachusett Mountain",
            "Ward Hill – Shrewsbury",
            "Warner Canyon – Lakeview",
            "Wasatch Peaks Ranch",
            "Waterville Valley",
            "Welch Village",
            "Wenatchee – Mission Ridge",
            "West Mountain",
            "Whaleback",
            "Whisper Ridge",
            "White Pass",
            "White Pine – Pinedale",
            "Whiteface – Lake Placid",
            "Whitefish Mountain Resort",
            "Whitetail",
            "Whitetail Ridge – Fort McCoy",
            "Wild Mountain",
            "Wildcat Mountain",
            "Willamette Pass – Crescent",
            "Willard Mountain – Greenwich",
            "Wilmot Mountain",
            "Windham Mountain",
            "Winter Park Resort",
            "Winter Park – Kewaunee County",
            "WinterClub Indoor Ski & Snowboard – Winter Park (dry slopes)",
            "Wintergreen Resort",
            "Winterplace",
            "Wisp – McHenry (Deep Creek Lake)",
            "Wolf Creek",
            "Wolf Ridge",
            "Woodbury  (temporarily closed)",
            "Woods Valley",
            "Woodward Park City",
            "Yawgoo Valley",
            "Yellowstone Club",
            "Yukon Alpine Heliskiing"
    };
}
